/**
 * Country name or ISO alpha-2 code → flag emoji. Names mirror the catalogue's
 * country list, so a stored venue.country resolves exactly. Two regional
 * indicator symbols; "" when unresolved so callers can guard. (Windows draws
 * the two letters instead of a flag; phones and Macs draw the flag, which is
 * where a public events page is read.)
 */
const NAMES: Record<string, string[]> = {
  AD: ["andorra"],
  AE: ["united arab emirates"],
  AF: ["afghanistan"],
  AG: ["antigua and barbuda"],
  AL: ["albania"],
  AM: ["armenia"],
  AO: ["angola"],
  AR: ["argentina"],
  AT: ["austria"],
  AU: ["australia"],
  AZ: ["azerbaijan"],
  BA: ["bosnia and herzegovina"],
  BB: ["barbados"],
  BD: ["bangladesh"],
  BE: ["belgium"],
  BF: ["burkina faso"],
  BG: ["bulgaria"],
  BH: ["bahrain"],
  BI: ["burundi"],
  BJ: ["benin"],
  BN: ["brunei"],
  BO: ["bolivia"],
  BR: ["brazil"],
  BS: ["bahamas"],
  BT: ["bhutan"],
  BW: ["botswana"],
  BY: ["belarus"],
  BZ: ["belize"],
  CA: ["canada"],
  CD: ["congo (dr)"],
  CF: ["central african republic"],
  CG: ["congo"],
  CH: ["switzerland"],
  CL: ["chile"],
  CM: ["cameroon"],
  CN: ["china"],
  CO: ["colombia"],
  CR: ["costa rica"],
  CU: ["cuba"],
  CV: ["cabo verde"],
  CY: ["cyprus"],
  CZ: ["czechia"],
  DE: ["germany"],
  DJ: ["djibouti"],
  DK: ["denmark"],
  DM: ["dominica"],
  DO: ["dominican republic"],
  DZ: ["algeria"],
  EC: ["ecuador"],
  EE: ["estonia"],
  EG: ["egypt"],
  ER: ["eritrea"],
  ES: ["spain"],
  ET: ["ethiopia"],
  FI: ["finland"],
  FJ: ["fiji"],
  FM: ["micronesia"],
  FR: ["france"],
  GA: ["gabon"],
  GB: ["united kingdom"],
  GD: ["grenada"],
  GE: ["georgia"],
  GH: ["ghana"],
  GM: ["gambia"],
  GN: ["guinea"],
  GQ: ["equatorial guinea"],
  GR: ["greece"],
  GT: ["guatemala"],
  GW: ["guinea-bissau"],
  GY: ["guyana"],
  HN: ["honduras"],
  HR: ["croatia"],
  HT: ["haiti"],
  HU: ["hungary"],
  ID: ["indonesia"],
  IE: ["ireland"],
  IL: ["israel"],
  IN: ["india"],
  IQ: ["iraq"],
  IR: ["iran"],
  IS: ["iceland"],
  IT: ["italy"],
  JM: ["jamaica"],
  JO: ["jordan"],
  JP: ["japan"],
  KE: ["kenya"],
  KG: ["kyrgyzstan"],
  KH: ["cambodia"],
  KI: ["kiribati"],
  KM: ["comoros"],
  KN: ["saint kitts and nevis"],
  KP: ["korea (north)"],
  KR: ["korea (south)"],
  KW: ["kuwait"],
  KZ: ["kazakhstan"],
  LA: ["laos"],
  LB: ["lebanon"],
  LC: ["saint lucia"],
  LI: ["liechtenstein"],
  LK: ["sri lanka"],
  LR: ["liberia"],
  LS: ["lesotho"],
  LT: ["lithuania"],
  LU: ["luxembourg"],
  LV: ["latvia"],
  LY: ["libya"],
  MA: ["morocco"],
  MC: ["monaco"],
  MD: ["moldova"],
  ME: ["montenegro"],
  MG: ["madagascar"],
  MH: ["marshall islands"],
  MK: ["north macedonia"],
  ML: ["mali"],
  MM: ["myanmar"],
  MN: ["mongolia"],
  MR: ["mauritania"],
  MT: ["malta"],
  MU: ["mauritius"],
  MV: ["maldives"],
  MW: ["malawi"],
  MX: ["mexico"],
  MY: ["malaysia"],
  MZ: ["mozambique"],
  NA: ["namibia"],
  NE: ["niger"],
  NG: ["nigeria"],
  NI: ["nicaragua"],
  NL: ["netherlands"],
  NO: ["norway"],
  NP: ["nepal"],
  NR: ["nauru"],
  NZ: ["new zealand"],
  OM: ["oman"],
  PA: ["panama"],
  PE: ["peru"],
  PG: ["papua new guinea"],
  PH: ["philippines"],
  PK: ["pakistan"],
  PL: ["poland"],
  PS: ["palestine"],
  PT: ["portugal"],
  PW: ["palau"],
  PY: ["paraguay"],
  QA: ["qatar"],
  RO: ["romania"],
  RS: ["serbia"],
  RU: ["russia"],
  RW: ["rwanda"],
  SA: ["saudi arabia"],
  SB: ["solomon islands"],
  SC: ["seychelles"],
  SD: ["sudan"],
  SE: ["sweden"],
  SG: ["singapore"],
  SI: ["slovenia"],
  SK: ["slovakia"],
  SL: ["sierra leone"],
  SM: ["san marino"],
  SN: ["senegal"],
  SO: ["somalia"],
  SR: ["suriname"],
  SS: ["south sudan"],
  ST: ["são tomé and príncipe"],
  SV: ["el salvador"],
  SY: ["syria"],
  SZ: ["eswatini"],
  TD: ["chad"],
  TG: ["togo"],
  TH: ["thailand"],
  TJ: ["tajikistan"],
  TL: ["timor-leste"],
  TM: ["turkmenistan"],
  TN: ["tunisia"],
  TO: ["tonga"],
  TR: ["turkey"],
  TT: ["trinidad and tobago"],
  TV: ["tuvalu"],
  TW: ["taiwan"],
  TZ: ["tanzania"],
  UA: ["ukraine"],
  UG: ["uganda"],
  US: ["united states"],
  UY: ["uruguay"],
  UZ: ["uzbekistan"],
  VC: ["saint vincent and the grenadines"],
  VE: ["venezuela"],
  VN: ["vietnam"],
  VU: ["vanuatu"],
  WS: ["samoa"],
  YE: ["yemen"],
  ZA: ["south africa"],
  ZM: ["zambia"],
  ZW: ["zimbabwe"],};

const LOOKUP = new Map<string, string>();
for (const [code, names] of Object.entries(NAMES)) {
  LOOKUP.set(code.toLowerCase(), code);
  for (const name of names) LOOKUP.set(name, code);
}

export function countryFlag(nameOrCode: string | null | undefined): string {
  if (!nameOrCode) return '';
  const code = LOOKUP.get(String(nameOrCode).trim().toLowerCase());
  if (!code) return '';
  return String.fromCodePoint(...[...code].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}
